os: windows

language: rust
script:
  - cargo build --verbose --workspace


deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "$TRAVIS_BUILD_DIR/target/debug/my_big_note.exe"
  skip_cleanup: true
  draft: true
  overwrite: true
