[package]
name = "my_big_note"
version = "0.1.0"
authors = ["Levitanus <pianoist@ya.ru>"]
publish = false

[dependencies]
iced = { version = "0.2", features = ["glow",  "tokio", "debug"] }
iced_native = "0.3"
chrono = "0.4"
midir = { version = "0.7", features = ["jack"] }